# Links on sidebar
menu:
  Home: /
  Categories: /categories/
  Tags: /tags/
  Archive: /archives/
  # Tags: /tags/
  # Categories: /categories/
  # About: /about/

# Pictures shown on the sidebar
# Use the absolute URL after generating
avatar: "/assets/favoricon.JPG"
sidebar_background: /assets/IMG_1454.JPG

rss: /atom.xml

# Content
excerpt_link: 继续 »

# Will be shown on the bottom.
## To add new icon, just copy .svg to source/assets/ and add entries below.
media:
  github: https://github.com/mmk982380365 
  # github: https://github.com/nameoverflow
  # facebook: https://www.facebook.com/profile.php?id=100004252391322

source_han_font: true

# Disqus settings
disqus:
  # 'disabled' | 'all' | 'post'
  enable: disabled
  # Shortname of your disqus website.
  # See disqus admin
  shortname:

# Miscellaneous
favicon:
